-- MySQL Script generated by MySQL Workbench
-- 07/19/16 12:17:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user_admin_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_admin_role` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '관리자 권한 테이블';


-- -----------------------------------------------------
-- Table `user_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_admin` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(200) NOT NULL COMMENT '이메일',
  `passwd` VARCHAR(40) NOT NULL,
  `role_id` VARCHAR(50) NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `receipt_email_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '이메일 수신여부',
  `error_email_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '오류내용 이메일수신여부',
  `login_cnt` INT NULL,
  `last_login_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_admin_role_idx`
    FOREIGN KEY (`role_id`)
    REFERENCES `user_admin_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '관리자 테이블';

CREATE INDEX `fk_admin_role_idx` ON `user_admin` (`role_id` ASC);


-- -----------------------------------------------------
-- Table `store_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_seller` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '지역가입자 SEQ',
  `admin_seq` BIGINT UNSIGNED NOT NULL COMMENT '지역가입자 로그인 정보 SEQ',
  `parent_seq` BIGINT UNSIGNED NULL COMMENT '지역가입자 부모 SEQ',
  `name` VARCHAR(100) NOT NULL COMMENT '지역가입자 명',
  `phone` VARCHAR(14) NOT NULL COMMENT '지역 가입자 전화번호',
  `use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_seller_admin_idx`
    FOREIGN KEY (`admin_seq`)
    REFERENCES `user_admin` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '지역사업자 테이블';

CREATE INDEX `fk_seller_admin_idx` ON `store_seller` (`admin_seq` ASC);


-- -----------------------------------------------------
-- Table `user_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manager` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(200) NOT NULL COMMENT '이메',
  `passwd` VARCHAR(40) NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '사장님명',
  `phone` VARCHAR(14) NULL COMMENT '전화번호',
  `subscription_channel` CHAR(1) NULL COMMENT '추천경로',
  `use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
COMMENT = '사장님 테이블';


-- -----------------------------------------------------
-- Table `store_root`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_root` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '가맹점주  SEQ',
  `seller_seq` BIGINT UNSIGNED NOT NULL COMMENT '지역가입자 SEQ',
  `manager_seq` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '가맹점 명',
  `sf_ver` VARCHAR(15) NULL COMMENT '스토어프렌즈 사용버전',
  `status` CHAR(1) NOT NULL DEFAULT '0' COMMENT '상태(0: 대기, 1: 무료사용, 2: 정상사용, 9: 테스트용 가맹점주)',
  `bizapp_use_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '사장님앱 사용여부',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_owner_seller_idx`
    FOREIGN KEY (`seller_seq`)
    REFERENCES `store_seller` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner_manager_idx`
    FOREIGN KEY (`manager_seq`)
    REFERENCES `user_manager` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점주 테이블';

CREATE INDEX `fk_owner_seller_idx` ON `store_root` (`seller_seq` ASC);

CREATE INDEX `fk_owner_manager_idx` ON `store_root` (`manager_seq` ASC);


-- -----------------------------------------------------
-- Table `user_manager_business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_manager_business` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager_seq` BIGINT UNSIGNED NOT NULL COMMENT '사용자 SEQ',
  `tax_id` VARCHAR(20) NULL COMMENT '사업자등록번호',
  `bank_code` VARCHAR(5) NULL COMMENT '은행코드',
  `bank_name` VARCHAR(10) NULL COMMENT '은행명',
  `bank_owner_name` VARCHAR(100) NULL COMMENT '은행고객명',
  `bank_account_no` VARCHAR(50) NULL COMMENT '은행번호',
  `card_no` VARCHAR(20) NULL,
  `card_name` VARCHAR(10) NULL,
  `card_valid_year` VARCHAR(2) NULL COMMENT '카드유효년도\n\n',
  `card_valid_month` VARCHAR(2) NULL COMMENT '카드 유효월',
  `billing_publish_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '청구서발행여부',
  `billing_issue_date` VARCHAR(2) NULL COMMENT '이체일',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_manager_business_manager_idx`
    FOREIGN KEY (`manager_seq`)
    REFERENCES `user_manager` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '사장님 사업 정보 테이블';

CREATE INDEX `fk_manager_business_manager_idx` ON `user_manager_business` (`manager_seq` ASC);


-- -----------------------------------------------------
-- Table `statistics_user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `statistics_user_login` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ADMIN / USER SEQ',
  `user_type` CHAR(1) NOT NULL COMMENT '사용자 타입(ADMIN, MANAGER)',
  `result_type` CHAR(1) NOT NULL COMMENT '결과(SUCCESS, FAIL)',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
COMMENT = '로그인 히스토리 테이블';


-- -----------------------------------------------------
-- Table `store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '가맹점 SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `seller_seq` BIGINT UNSIGNED NOT NULL COMMENT '지역사업자 SEQ',
  `name` VARCHAR(100) NULL COMMENT '가맹점 명',
  `phone` VARCHAR(14) NULL COMMENT '전화번호',
  `cell_phone` VARCHAR(14) NULL COMMENT '핸드폰번호',
  `virtual_phone` VARCHAR(14) NULL COMMENT '가상번호',
  `store_type` CHAR(1) NULL COMMENT '가맹점 형식 (0: 프리미엄, 1: 전자결제, 2: 콜링크)',
  `tts_use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ARS 사용여부',
  `tts_notify_use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ARS 알림 사용여부',
  `tts_phone` VARCHAR(14) NULL COMMENT 'ARS 전화번호',
  `tts_phone_etc` VARCHAR(14) NULL COMMENT 'ARS 보조 전화번호 ',
  `category` CHAR(2) NULL COMMENT '카테고리(0: 치킨, 1: 피자/햄버거, 2: 보쌈/족발, 3: 중식, 4: 도시락, 5: 한식/분식, 6: 회/일식/돈까스, 7: 야식/찜/탕, 10: 일반가맹점)',
  `push_server_url` VARCHAR(200) NULL,
  `delv_min_price` INT NULL,
  `delv_able_region_avbbv` VARCHAR(500) NULL,
  `logo_img_url` VARCHAR(300) NULL COMMENT '로고 이미지 URL',
  `paper_img_url` VARCHAR(300) NULL COMMENT '책자 이미지 URL',
  `use_store_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '매장판매여부',
  `use_delivery_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '배달판매여부',
  `use_package_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '포판매여부',
  `use_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_store_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 테이블';

CREATE INDEX `fk_store_root_idx` ON `store` (`root_seq` ASC);


-- -----------------------------------------------------
-- Table `store_cms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_cms` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'CMS SEQ',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `owner_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `type` CHAR(1) NOT NULL DEFAULT '0' COMMENT '타입 (0: 프리미엄, 1: 콜링크)',
  `bank_code` VARCHAR(5) NULL COMMENT '은행코드(002: 산업은행, 003: 기업은행, 004: 국민은행, 005: 외환은행, 007: 수협중앙회, 011: 농협은행, 012: 농협중앙회, 020: 우리은행, 023: SC은행, 027: 한국씨티은행, 031: 대구은행, 032: 부산은행, 034: 광주은행, 035: 제주은행, 037: 전북은행, 039: 경남은행, 045: 새마을금고, 048: 신협중앙회, 050: 상호저축은행, 054: HSBC은행, 071: 우체국, 081: 하나은행, 088: 신한은행)',
  `bank_owner_name` VARCHAR(100) NULL COMMENT '예금주 명',
  `bank_account_no` VARCHAR(50) NULL COMMENT '계좌번호',
  `withdrawal_info` VARCHAR(50) NULL COMMENT '출금정보(사업자번호 혹은 생년월일)',
  `withdrawal_cost` BIGINT NULL COMMENT '출금금액',
  `transfer_start_date` TIMESTAMP NULL COMMENT '이체시작일',
  `withdrawal_date` TIMESTAMP NULL COMMENT '출금일(매월)',
  `use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_cms_store`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 CMS 테이블';


-- -----------------------------------------------------
-- Table `user_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_employee` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '담당자 SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `manager_seq` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '담당자 명',
  `type` CHAR(1) NOT NULL COMMENT '구분(0: 일반, 1: 배달)',
  `code` VARCHAR(40) NOT NULL COMMENT '비밀번호',
  `work_start_date` CHAR(6) NULL COMMENT '근무시작일',
  `work_end_date` CHAR(6) NULL COMMENT '근무종료일',
  `birthday` CHAR(6) NULL COMMENT '생년월일',
  `phone` VARCHAR(14) NULL COMMENT '전화번호',
  `memo` VARCHAR(2000) NULL COMMENT '메모',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_employee_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_manager_idx`
    FOREIGN KEY (`manager_seq`)
    REFERENCES `user_manager` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '직원 테이블';

CREATE INDEX `fk_employee_root_idx` ON `user_employee` (`root_seq` ASC);

CREATE INDEX `fk_employee_manager_idx` ON `user_employee` (`manager_seq` ASC);


-- -----------------------------------------------------
-- Table `store_mobile_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_mobile_web` (
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `owner_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `name` VARCHAR(200) NOT NULL COMMENT '모바일 웹 명',
  `run24_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '24 운영여부',
  `open_year_round_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '연중무휴여부',
  `open_time` CHAR(4) NULL COMMENT '간운영시작시간',
  `close_time` CHAR(4) NULL COMMENT '운영종료시',
  `off_week` CHAR(1) NOT NULL DEFAULT '0' COMMENT '주중 쉬는 요일',
  `off_day` CHAR(1) NOT NULL DEFAULT '0' COMMENT '쉬는 일',
  `tmp_off_startdate` TIMESTAMP NULL COMMENT '임시 휴일(시작일)',
  `tmp_off_enddate` TIMESTAMP NULL COMMENT '임시 휴일(종료일)',
  `start_date` TIMESTAMP NULL COMMENT '모바일 홈페이지 서비스 시작일',
  `end_date` TIMESTAMP NULL COMMENT '모바일 홈페이지 서비스 종료일',
  `use_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '사용여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`store_seq`),
  CONSTRAINT `fk_mobile_web_schedule_store_idx`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 모바일 홈페이지 테이블';


-- -----------------------------------------------------
-- Table `store_root_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_root_address` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '가맹점주 주소 SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `type` CHAR(1) NULL COMMENT '타입(0: 대표 주소, 1: 보조 주소, 2: 배달가능지역)',
  `postcode` VARCHAR(7) NULL COMMENT '구우편번호',
  `zonecode` VARCHAR(50) NULL COMMENT '국가기초구역번호',
  `bcode` VARCHAR(50) NULL COMMENT '법정동/법정리 코드',
  `bname` VARCHAR(20) NULL COMMENT '법정동/법정리 명',
  `bldg_code` VARCHAR(50) NULL COMMENT '건물관리번호',
  `bldg_name` VARCHAR(50) NULL COMMENT '건물명',
  `post_address` VARCHAR(200) NULL COMMENT '도로명 주소',
  `legacy_post_address` VARCHAR(200) NULL COMMENT '지번주소',
  `detail_post_address` VARCHAR(200) NULL COMMENT '상세주소',
  `gps_lat` VARCHAR(25) NULL COMMENT '위도',
  `gps_lng` VARCHAR(25) NULL COMMENT '경도',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_root_address_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점주 주소 테이블';

CREATE INDEX `fk_root_address_root_idx` ON `store_root_address` (`root_seq` ASC);


-- -----------------------------------------------------
-- Table `store_floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_floor` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '층 SEQ',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `name` VARCHAR(20) NOT NULL COMMENT '층 명',
  `display_order` INT UNSIGNED NOT NULL COMMENT '노출 순번',
  `use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부(0: false, 1: true)',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부(0: false, 1: true)',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_floor_store_idx`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 층 정보 테이블';

CREATE INDEX `fk_floor_store_idx` ON `store_floor` (`store_seq` ASC);


-- -----------------------------------------------------
-- Table `store_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_table` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '테이블 SEQ',
  `floor_seq` BIGINT UNSIGNED NOT NULL COMMENT '층 SEQ',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `name` VARCHAR(20) NOT NULL COMMENT '테이블명',
  `display_order` INT NULL COMMENT '노출 순번',
  `use_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '사용여부',
  `del_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_table_floor_idx`
    FOREIGN KEY (`floor_seq`)
    REFERENCES `store_floor` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 테이블정보 테이블';

CREATE INDEX `fk_table_floor_idx` ON `store_table` (`floor_seq` ASC);


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '카테고리 SEQ',
  `name` VARCHAR(20) NOT NULL COMMENT '카테고리 명',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
COMMENT = '기본 카테고리 테이블';


-- -----------------------------------------------------
-- Table `category_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category_store` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '가맹점 카테고리 SEQ',
  `category_seq` BIGINT UNSIGNED NOT NULL COMMENT '기본 카테고리 SEQ',
  `owner_seq` BIGINT UNSIGNED NULL COMMENT '가맹점주 SEQ',
  `store_seq` BIGINT UNSIGNED NULL COMMENT '가맹점 SEQ',
  `name` VARCHAR(20) NULL COMMENT '가맹점 명',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_category_store_category_idx`
    FOREIGN KEY (`category_seq`)
    REFERENCES `category` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 카테고리 테이블';

CREATE INDEX `fk_category_store_category_idx` ON `category_store` (`category_seq` ASC);


-- -----------------------------------------------------
-- Table `menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메뉴 SEQ',
  `owner_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `category_store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 카테고리 SEQ',
  `store_seq` BIGINT NULL COMMENT '가맹점 SEQ',
  `name` VARCHAR(200) NULL COMMENT '메뉴명',
  `price` INT NULL COMMENT '가격',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_menu_category_store`
    FOREIGN KEY (`category_store_seq`)
    REFERENCES `category_store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 메뉴 테이블';

CREATE INDEX `fk_menu_category_store_idx` ON `menu` (`category_store_seq` ASC);


-- -----------------------------------------------------
-- Table `option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `option` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '옵션 SEQ',
  `owner_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `name` VARCHAR(200) NOT NULL COMMENT '옵션명',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
COMMENT = '옵션 테이블';


-- -----------------------------------------------------
-- Table `mapping_menu_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapping_menu_option` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '메뉴옵션 SEQ',
  `menu_seq` BIGINT UNSIGNED NOT NULL COMMENT '메뉴 SEQ',
  `option_seq` BIGINT UNSIGNED NOT NULL COMMENT '옵션 SEQ',
  `type` CHAR(1) NOT NULL DEFAULT '0' COMMENT '타입(0: 선택, 1: 필수)',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_mapping_menu_option_menu_idx`
    FOREIGN KEY (`menu_seq`)
    REFERENCES `menu` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mapping_menu_option_option_idx`
    FOREIGN KEY (`option_seq`)
    REFERENCES `option` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 메뉴, 옵션 매핑 테이블';

CREATE INDEX `fk_mapping_menu_option_menu_idx` ON `mapping_menu_option` (`menu_seq` ASC);

CREATE INDEX `fk_mapping_menu_option_option_idx` ON `mapping_menu_option` (`option_seq` ASC);


-- -----------------------------------------------------
-- Table `option_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `option_detail` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '옵션 상세 SEQ',
  `option_seq` BIGINT UNSIGNED NOT NULL COMMENT '옵션 SEQ',
  `name` VARCHAR(200) NOT NULL COMMENT '옵션 상세 명',
  `price` INT NOT NULL DEFAULT 0 COMMENT '옵션 상세 가격',
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_option_detail_option_idx`
    FOREIGN KEY (`option_seq`)
    REFERENCES `option` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '옵션 상세 테이블';

CREATE INDEX `fk_option_detail_option_idx` ON `option_detail` (`option_seq` ASC);


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '주문 SEQ',
  `seller_seq` BIGINT UNSIGNED NOT NULL,
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `cid_seq` BIGINT UNSIGNED NOT NULL COMMENT 'CID SEQ',
  `floor_seq` BIGINT UNSIGNED NULL COMMENT '층 정보 SEQ',
  `table_seq` BIGINT UNSIGNED NULL COMMENT '테이블 SEQ',
  `order_no` BIGINT UNSIGNED NOT NULL COMMENT '주문번호',
  `payment_type` CHAR(1) NULL COMMENT '결제타입(0: 현금, 1: 카드, 2: 페이나우)',
  `status_order` CHAR(1) NULL COMMENT '주문 상태',
  `status_refund` CHAR(1) NULL COMMENT '환불 상태',
  `paynow_order_yn` CHAR(1) NULL DEFAULT 'N' COMMENT '페이나우 주문 여부',
  `paynow_memo` VARCHAR(300) NULL COMMENT '페이나우 메모',
  `paynow_advance` CHAR(1) NULL COMMENT '페이나우 선정산 여부',
  `order_path` CHAR(1) NULL COMMENT '주문경로',
  `order_reject_message` VARCHAR(300) NULL COMMENT '주문 취소 메시지(가맹점에서 취소 시에 사용)',
  `total_price` INT NULL DEFAULT 0 COMMENT '주문 총 금액',
  `discount_type` CHAR(1) NULL DEFAULT '0' COMMENT '할인타입(0: 금액, 1: 퍼센트)',
  `discount_price` INT NULL DEFAULT 0 COMMENT '할인 금액',
  `discount_rate` DECIMAL(3,1) NULL DEFAULT 0.0 COMMENT '할인율',
  `use_point` INT NULL COMMENT '포인트 사용',
  `payment_price` INT NULL COMMENT '최종 결재 금액',
  `save_point` INT NULL COMMENT '적립 포인트',
  `nopay_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '외상여부',
  `moddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_order_store_idx`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '주문 테이블';

CREATE INDEX `fk_order_store_idx` ON `order` (`store_seq` ASC);


-- -----------------------------------------------------
-- Table `order_push_tts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_push_tts` (
  `order_seq` BIGINT UNSIGNED NOT NULL COMMENT '주문 SEQ',
  `order_no` BIGINT UNSIGNED NOT NULL COMMENT '주문 번호',
  `push_delay_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '지연 여부',
  `push_notify_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '통지 여부',
  `push_complete_message` VARCHAR(300) NULL COMMENT '완료 메시지',
  `push_fail_message` VARCHAR(300) NULL COMMENT '실패 메시지',
  `tts_use_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ARS 여부',
  `tts_missed_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'ARS 실패여부',
  `tts_fail_messgae` VARCHAR(300) NULL COMMENT 'ARS 수신 실패 메시지',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`order_seq`),
  CONSTRAINT `fk_push_order_idx`
    FOREIGN KEY (`order_seq`)
    REFERENCES `order` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '주문 PUSH 및 TTS 정보 테이블';


-- -----------------------------------------------------
-- Table `order_commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_commission` (
  `order_seq` BIGINT UNSIGNED NOT NULL COMMENT '주문 SEQ',
  `type` CHAR(1) NOT NULL DEFAULT '0' COMMENT '수수료 타입(0: 수수료없음, 1: 퍼센트[%, 주문건], 2: 금액[원, 주문건])',
  `rate` DECIMAL(3,1) NULL DEFAULT 0.0 COMMENT '수수료율',
  `price` INT NULL DEFAULT 0 COMMENT '수수료금액',
  `head_rate` DECIMAL(3,1) NOT NULL DEFAULT 0.0 COMMENT '본사 수수료율',
  `head_price` INT NOT NULL DEFAULT 0 COMMENT '본사 수수료금액',
  `pg_rate` DECIMAL(3,1) NOT NULL DEFAULT 0.0 COMMENT 'pg사 수수료율',
  `pg_price` INT NOT NULL DEFAULT 0 COMMENT 'pg사 수수료 금액',
  `pg_vat_rate` DECIMAL(3,1) NOT NULL DEFAULT 0.0 COMMENT 'pg사 부가세율',
  `pg_vat_price` INT NOT NULL DEFAULT 0 COMMENT 'pg사 부가세 금액',
  `sms_price` INT NOT NULL DEFAULT 0 COMMENT 'sms 단가',
  `seller_price` INT NOT NULL DEFAULT 0 COMMENT '지역사업자 수수료율',
  `owner_price` INT NOT NULL DEFAULT 0 COMMENT '가맹점주 수수료 금액',
  `transfer_price` INT NOT NULL DEFAULT 0 COMMENT '이제 금액',
  `charge_price` INT NOT NULL DEFAULT 0 COMMENT '결제 수수료',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`order_seq`),
  CONSTRAINT `fk_commission_order_idx`
    FOREIGN KEY (`order_seq`)
    REFERENCES `order` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '주문 수수료 테이블';


-- -----------------------------------------------------
-- Table `order_delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_delivery` (
  `order_seq` BIGINT UNSIGNED NOT NULL COMMENT '주문 SEQ',
  `collect_yn` CHAR(1) NOT NULL DEFAULT '0' COMMENT '그릇 수거 여부(0: false, 1: true)',
  `collect_employee_seq` BIGINT NULL COMMENT '그릇 수거 직원 SEQ',
  `delivery_yn` CHAR(1) NOT NULL DEFAULT '0' COMMENT '배달 여부(0: false, 1: true)',
  `delivery_employee_seq` BIGINT NULL COMMENT '배달 직원 SEQ',
  `delivery_employee_name` VARCHAR(30) NULL COMMENT '배달 직원 명',
  `delivery_employee_phone` VARCHAR(14) NULL COMMENT '배달 직원 번호',
  `regdate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`order_seq`),
  CONSTRAINT `fk_delivery_order_idx`
    FOREIGN KEY (`order_seq`)
    REFERENCES `order` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '주문 배달 테이블';


-- -----------------------------------------------------
-- Table `statistics_order_daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `statistics_order_daily` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '일일주문통계 SEQ',
  `owner_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `operdate` CHAR(6) NULL COMMENT '주문일',
  `sales` MEDIUMTEXT NULL COMMENT '주문 통계',
  `start_date` TIMESTAMP NULL COMMENT '운영시간 시작일',
  `end_date` TIMESTAMP NULL COMMENT '운영시간 종료일',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`))
ENGINE = InnoDB
COMMENT = '가맹점 일일 주문 통계 테이블';


-- -----------------------------------------------------
-- Table `user_cid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_cid` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'CID 주문 SEQ',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 SEQ',
  `phone` VARCHAR(14) NULL COMMENT '전화번호',
  `phone_etc` VARCHAR(45) NULL COMMENT '추가 전화 번호',
  `postcode` VARCHAR(7) NULL COMMENT '구 우편번호',
  `zonecode` VARCHAR(50) NULL COMMENT '국가기초구역번호',
  `bcode` VARCHAR(50) NULL COMMENT '법정동/법정리 코드',
  `bname` VARCHAR(20) NULL COMMENT '법정동/법정리 명',
  `bldg_code` VARCHAR(50) NULL COMMENT '건물관리번호',
  `bldg_name` VARCHAR(50) NULL COMMENT '건물명',
  `post_address` VARCHAR(100) NULL COMMENT '도로명 주소',
  `legacy_post_address` VARCHAR(100) NULL COMMENT '지번주소',
  `detail_post_address` VARCHAR(150) NULL COMMENT '상세주소',
  `gps_lat` VARCHAR(25) NULL COMMENT '위도',
  `gps_lng` VARCHAR(25) NULL COMMENT '경도',
  `memo` VARCHAR(2000) NULL COMMENT '메모',
  `nopay_sum` INT NOT NULL DEFAULT 0 COMMENT '외상 합계',
  `moddate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수정일',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_user_cid_store_idx`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'CID 주문 고객 정보 테이블';

CREATE INDEX `fk_user_cid_store_idx` ON `user_cid` (`store_seq` ASC);


-- -----------------------------------------------------
-- Table `user_cid_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_cid_address` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'CID 주문 주소 SEQ',
  `cid_seq` BIGINT UNSIGNED NOT NULL COMMENT 'CID 주문 SEQ',
  `postcode` VARCHAR(7) NULL COMMENT '구 우편번호',
  `zonecode` VARCHAR(50) NULL COMMENT '국가기초구역번호',
  `bcode` VARCHAR(50) NULL COMMENT '법정동/법정리 코드',
  `bname` VARCHAR(20) NULL COMMENT '법정동/법정리 명',
  `bldg_code` VARCHAR(50) NULL COMMENT '건물관리번호',
  `bldg_name` VARCHAR(50) NULL COMMENT '건물명',
  `post_address` VARCHAR(100) NULL COMMENT '도로명 주소',
  `legacy_post_address` VARCHAR(100) NULL COMMENT '지번주소',
  `detail_post_address` VARCHAR(150) NULL COMMENT '상세 주소',
  `gps_lat` VARCHAR(25) NULL COMMENT '위도',
  `gps_lng` VARCHAR(25) NULL COMMENT '경도',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_address_cid_user_cid_idx`
    FOREIGN KEY (`cid_seq`)
    REFERENCES `user_cid` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'CID 주문 고객 주소 정보 테이블';

CREATE INDEX `fk_address_cid_user_cid_idx` ON `user_cid_address` (`cid_seq` ASC);


-- -----------------------------------------------------
-- Table `store_cid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_cid` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'CID SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 코드',
  `store_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점 코드',
  `cid_no` VARCHAR(14) NOT NULL COMMENT 'CID 번호',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_store_cid_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_store_cid_store_idx`
    FOREIGN KEY (`store_seq`)
    REFERENCES `store` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'CID 테이블';

CREATE INDEX `fk_store_cid_root_idx` ON `store_cid` (`root_seq` ASC);

CREATE INDEX `fk_store_cid_store_idx` ON `store_cid` (`store_seq` ASC);


-- -----------------------------------------------------
-- Table `store_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_operation` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '운영시간 SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL COMMENT '가맹점주 SEQ',
  `oper_date` CHAR(6) NOT NULL COMMENT '운영일',
  `start_date` TIMESTAMP NULL COMMENT '운영 시작시간',
  `end_date` TIMESTAMP NULL COMMENT '운영 종료일',
  `reserve_fund` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '준비금',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_operation_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 운영시간 테이블';

CREATE INDEX `fk_operation_root_idx` ON `store_operation` (`root_seq` ASC);


-- -----------------------------------------------------
-- Table `user_pos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_pos` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'POS 정보 SEQ',
  `manager_seq` BIGINT UNSIGNED NOT NULL COMMENT '사장님 SEQ',
  `root_seq` BIGINT UNSIGNED NOT NULL,
  `type` CHAR(1) NOT NULL DEFAULT '0' COMMENT 'POS타입 (0: MAIN, 1: ETC)',
  `mac_address` VARCHAR(100) NOT NULL,
  `del_yn` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_pos_manager_idx`
    FOREIGN KEY (`manager_seq`)
    REFERENCES `user_manager` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pos_root_idx`
    FOREIGN KEY (`root_seq`)
    REFERENCES `store_root` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '가맹점 POS 정보 테이블';

CREATE INDEX `fk_pos_manager_idx` ON `user_pos` (`manager_seq` ASC);

CREATE INDEX `fk_pos_owner_idx_idx` ON `user_pos` (`root_seq` ASC);


-- -----------------------------------------------------
-- Table `store_user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_user_login` (
  `seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '로그인 SEQ',
  `operation_seq` BIGINT UNSIGNED NOT NULL COMMENT '운영 SEQ',
  `login_date` TIMESTAMP NULL COMMENT '로그인 시간',
  `logout_date` TIMESTAMP NULL COMMENT '로그아웃 시간',
  `user_seq` BIGINT UNSIGNED NOT NULL COMMENT '로그인 사용자 SEQ',
  `user_type` CHAR(1) NOT NULL DEFAULT '0' COMMENT '로그인 사용자 타입(0: MANAGER, 1: EMPLOYEE)',
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
  PRIMARY KEY (`seq`),
  CONSTRAINT `fk_user_login_operation_idx`
    FOREIGN KEY (`operation_seq`)
    REFERENCES `store_operation` (`seq`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '클라이언트 로그인 정보 테이블';

CREATE INDEX `fk_user_login_operation_idx_idx` ON `store_user_login` (`operation_seq` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

